# Claude Code Web GUI - GitHub Pages Configuration

# Site settings
title: Claude Code Web GUI
description: A simple and practical Claude Code session browser that runs entirely in your browser
author: binggg

# GitHub Pages URL (will be automatically set by GitHub)
# url and baseurl will be automatically configured by GitHub Pages

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - server/
  - doc/
  - .gitignore
  - README_ZH.md
  - todo.md
  - claude-color.svg
  - assets/js/temp_methods.txt
  - .github/
  - LICENSE

# Plugin settings (GitHub Pages supported)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en
locale: en_US

# Social
github_username: binggg